### ISSUE TITLE
Real-Debrid add into this project.

### ISSUE THREAD

**Issue by ericvlog** [arvida42/jackettio#2]
Please add a real-debrid support because it quite well knows debrid services.

Thanks you.

**Comment by ericvlog** [comment]
Really thanks for integrate rd, your addon wonderful parse foreign movie/tvshow title name.

For movie it wonderful play with RD+.

Just I found out for some russian show, it show rd+ but still add to debrid without direct play.
but the log of addon say got found on rd cache

TV-show name = High Tides (2023)

2024-02-26T20:30:43.470415760Z tt21093806:1:2 : 10 files found
2024-02-26T20:30:41.400069843Z tt21093806:1:2 : get files ...
2024-02-26T20:30:42.325042453Z tt21093806-1-3 : 16 torrents found in 26.159s
2024-02-26T20:30:41.393299266Z GET /*******************/download/series/tt21093806:1:2/13af7124131d5e401213e1d852df1adc1bc94df9
2024-02-26T20:30:42.325650802Z tt21093806-1-3 : 16 torrents filtered, get torrents infos ...
2024-02-26T20:30:42.859327044Z tt21093806-1-3 : 7 torrents infos found in 0.533s
2024-02-26T20:30:43.163159609Z tt21093806-**1-3 : 2 cached torrents on RD**
2024-02-26T20:30:43.900814976Z tt21093806-1-3 : Searching torrents ...
2024-02-26T20:30:43.926308343Z Error: File not ready on debrid
2024-02-26T20:30:43.926393330Z     at RealDebrid.getDownload (file:///home/node/app/src/lib/debrid/realdebrid.js:71:13)
2024-02-26T20:30:43.926412813Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-26T20:30:43.926430100Z     at async Module.getDownload (file:///home/node/app/src/lib/jackettio.js:299:18)
2024-02-26T20:30:43.926446481Z     at async file:///home/node/app/src/index.js:106:17

**Comment by arvida42** [comment]
Real-debrid API is the worst API ... However, this is the first version of RD integration and need some rework.

**Comment by ericvlog** [comment]
Sorry I open new issues regarding this.....Thank you so much. 
Appreciate.
