### ISSUE TITLE
Some TV-shows no play direct even have cache on rd+ from tvpack.

### ISSUE THREAD

**Issue by ericvlog** [arvida42/jackettio#3]
Below is log addons, from 2 tvshow while same torrent have cache on real-debrid by Torrentio.

Thanks for your wonderful addons. It awesom well & fast movies played.

2024-02-26T21:36:29.544916740Z GET /*******************/download/series/tt23025212:1:3/d5272bb685df7ac512698e8a5cbbb264877ec745
2024-02-26T21:36:29.546046159Z tt23025212:1:3 : get files ...
2024-02-26T21:36:31.197143119Z tt23025212:1:3 : 8 files found
2024-02-26T21:36:31.698875985Z Error: File not ready on debrid
2024-02-26T21:36:31.698932149Z     at RealDebrid.getDownload (file:///home/node/app/src/lib/debrid/realdebrid.js:71:13)
2024-02-26T21:36:31.698941746Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-26T21:36:31.698949856Z     at async Module.getDownload (file:///home/node/app/src/lib/jackettio.js:299:18)
2024-02-26T21:36:31.698957676Z     at async file:///home/node/app/src/index.js:106:17
2024-02-26T21:36:31.803510441Z tt23025212:1:3 : get files ...
2024-02-26T21:36:33.537475445Z tt23025212:1:3 : 8 files found
2024-02-26T21:36:34.049909472Z Error: File not ready on debrid
2024-02-26T21:36:34.050015899Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-26T21:36:34.049995394Z     at RealDebrid.getDownload (file:///home/node/app/src/lib/debrid/realdebrid.js:71:13)
2024-02-26T21:36:34.050033565Z     at async Module.getDownload (file:///home/node/app/src/lib/jackettio.js:299:18)
2024-02-26T21:36:34.050050399Z     at async file:///home/node/app/src/index.js:106:17

——————————————————————————————————————————————————

2024-02-26T21:42:31.033148625Z tt6563112-1-2 : 17 indexers selected : IPTorrents, RuTracker, The Pirate Bay, UnionDHT, EZTV, NoNaMe Club, TorrentLeech, LimeTorrents, BitSearch, kickasstorrents.ws, RuTracker.RU, Torrent9, TheRARBG, Solid Torrents, RuTor, MegaPeer, Nyaa.si
2024-02-26T21:42:30.818028325Z GET /*******************/download/series/tt6563112:1:1/83b9980638d839ecae5de70ffd555c04409b88a3
2024-02-26T21:42:31.064746044Z tt6563112-1-2 : 78 torrents found in 0.27s
2024-02-26T21:42:31.066196569Z tt6563112-1-2 : 17 torrents filtered, get torrents infos ...
2024-02-26T21:42:31.080364479Z tt6563112-1-2 : 7 torrents infos found in 0.013s
2024-02-26T21:42:32.466743793Z tt6563112:1:1 : 7 files found
2024-02-26T21:42:33.228458118Z Error: File not ready on debrid
2024-02-26T21:42:31.273388532Z tt6563112-1-2 : 1 cached torrents on RD
2024-02-26T21:42:33.228543838Z     at RealDebrid.getDownload (file:///home/node/app/src/lib/debrid/realdebrid.js:71:13)
2024-02-26T21:42:33.228604735Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-26T21:42:33.228624201Z     at async Module.getDownload (file:///home/node/app/src/lib/jackettio.js:299:18)
2024-02-26T21:42:33.228641122Z     at async file:///home/node/app/src/index.js:106:17

**Comment by arvida42** [comment]
I made some fix on RD cache in the last release

**Comment by ericvlog** [comment]
It working now, add 3 same torrents to rd also solved, 

Thanks very much ~~!!

**Comment by arvida42** [comment]
Could you give version 1.1.3 a try? In this latest release, all videos within torrents are now added to RD when not cached and it includes a feature to detect and prevent duplicates in your RD library. I recommend cleaning up your RD torrents to ensure smooth operation and avoid any potential issues.

**Comment by ericvlog** [comment]
hello, I try out the latest version all the problem is solved. 👍 

Just ask how jackettio handle title? It uses original titles or release titles? I noticed rutor, rutracker Russian tracker very hard get Russian movies source if no use original titles.  

IMDB meta have International / Original language title name?

By now, playback on Movies, Tvshow on Cache RD / Uncache add to RD download running very well.

**Comment by ericvlog** [comment]
Hello, I noobs, for max result should choose Strip Cyrillic Letters, and for max quality should Sort requested from site by Size Desc in Jackett, Then I can get far better result same par with torrentio even better.

Thanks for wonderful addon,
