### ISSUE TITLE
Placeholder stream when selected file is uncached on debrid

### ISSUE THREAD

**Issue by FireMasterK** [arvida42/jackettio#36]
Currently, you get a server-side error:
```
tt1234 Error: File not ready on debrid
    at #getFilesFromTorrent (file:///home/node/app/src/lib/debrid/debridlink.js:81:13)
    at DebridLink.getFilesFromMagnet (file:///home/node/app/src/lib/debrid/debridlink.js:54:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.getDownload (file:///home/node/app/src/lib/jackettio.js:409:13)
    at async file:///home/node/app/src/index.js:177:17
```

It would be nice if we could play a dummy 30s stream, like torrentio or similar to indicate the file has been added to the debris service.

Edit: It looks like [the file](https://github.com/arvida42/jackettio/blob/master/src/static/videos/not_ready.mp4) does exist, maybe this error just needs to be handled for debrid-link? :thinking:

**Comment by FireMasterK** [comment]
Seemed to be a one-off error. I can't reproduce anymore.
